### PR TITLE
Revert "Update code.c"

### PR DESCRIPTION
**Pull request by 3words**
Reverts csci3250-2019/project-team-c#29

### CODE REVIEW

**Comment by 3words** [comment]
saw someone mess up code.c file cause other branch unable to merge, someone please accept to revert the branch

**Comment by LareinaM** [comment]
@AlbertngSeadragon plz review this so that we could move on

**Comment by 3words** [comment]
> @AlbertngSeadragon plz review this so that we could move on



> @AlbertngSeadragon plz review this so that we could move on

@LareinaM can you help to do the preview?

**Comment by LareinaM** [comment]
hey use the ; instead of , in the loop

**Comment by AlbertngSeadragon** [comment]
Really sorry for my mistake, but i dont find the pull request, it seem the review for your pull request is not appear

**Pull request merged**
